# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nahook < Formula
  desc "The Nahook command-line tool — trigger events, inspect deliveries, manage endpoints."
  homepage "https://nahook.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getnahook/nahook-cli/releases/download/v0.1.0/nahook_0.1.0_macos_amd64.tar.gz"
      sha256 "b0d32df343ed96ad9c968bb32efbdcd835f3c42706fa1670aa930cd7b143dd92"

      define_method(:install) do
        bin.install "nahook"
        # Install shell completions generated by the binary so users get
        # tab-complete out of the box when they upgrade via brew.
        generate_completions_from_executable(bin/"nahook", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getnahook/nahook-cli/releases/download/v0.1.0/nahook_0.1.0_macos_arm64.tar.gz"
      sha256 "4187c252d1ed4c896fc2c5f9715125947cc463facaf4f07487098957a4ed793e"

      define_method(:install) do
        bin.install "nahook"
        # Install shell completions generated by the binary so users get
        # tab-complete out of the box when they upgrade via brew.
        generate_completions_from_executable(bin/"nahook", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getnahook/nahook-cli/releases/download/v0.1.0/nahook_0.1.0_linux_amd64.tar.gz"
      sha256 "a7a99271d272ac8f4ddc9a6571c836cce9f8359eff4c8ecf58ab09a240795419"
      define_method(:install) do
        bin.install "nahook"
        # Install shell completions generated by the binary so users get
        # tab-complete out of the box when they upgrade via brew.
        generate_completions_from_executable(bin/"nahook", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getnahook/nahook-cli/releases/download/v0.1.0/nahook_0.1.0_linux_arm64.tar.gz"
      sha256 "e9b6fc916959aeaa24a0c77d402d18b99a8a23e4e647623abe8a13e9403ed092"
      define_method(:install) do
        bin.install "nahook"
        # Install shell completions generated by the binary so users get
        # tab-complete out of the box when they upgrade via brew.
        generate_completions_from_executable(bin/"nahook", "completion")
      end
    end
  end

  test do
    system "#{bin}/nahook", "--version"
  end
end
