# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nahook < Formula
  desc "The Nahook command-line tool — trigger events, inspect deliveries, manage endpoints."
  homepage "https://nahook.com"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getnahook/nahook-cli/releases/download/v0.2.1/nahook_0.2.1_macos_amd64.tar.gz"
      sha256 "6f7410f2367b4fab490aa7f2387a92d7b837bb1ec84f6f2f3523084e08a8e644"

      define_method(:install) do
        bin.install "nahook"
        # Install shell completions generated by the binary so users get
        # tab-complete out of the box when they upgrade via brew.
        generate_completions_from_executable(bin/"nahook", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getnahook/nahook-cli/releases/download/v0.2.1/nahook_0.2.1_macos_arm64.tar.gz"
      sha256 "fcdc253126e1f34954778dec77de1a94ec127b4397226a56178274f1f455fb62"

      define_method(:install) do
        bin.install "nahook"
        # Install shell completions generated by the binary so users get
        # tab-complete out of the box when they upgrade via brew.
        generate_completions_from_executable(bin/"nahook", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getnahook/nahook-cli/releases/download/v0.2.1/nahook_0.2.1_linux_amd64.tar.gz"
      sha256 "6e0d583b4891dd0aa0f85031ababcd744910116555570d94f2c5c96b2b4cd923"
      define_method(:install) do
        bin.install "nahook"
        # Install shell completions generated by the binary so users get
        # tab-complete out of the box when they upgrade via brew.
        generate_completions_from_executable(bin/"nahook", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getnahook/nahook-cli/releases/download/v0.2.1/nahook_0.2.1_linux_arm64.tar.gz"
      sha256 "a6dc3efcdb98a06119341de606ac23a90aa75cc012997c0f9f9f8cbf44f11d6a"
      define_method(:install) do
        bin.install "nahook"
        # Install shell completions generated by the binary so users get
        # tab-complete out of the box when they upgrade via brew.
        generate_completions_from_executable(bin/"nahook", "completion")
      end
    end
  end

  test do
    system "#{bin}/nahook", "--version"
  end
end
