# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nahook < Formula
  desc "The Nahook command-line tool — trigger events, inspect deliveries, manage endpoints."
  homepage "https://nahook.com"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getnahook/nahook-cli/releases/download/v0.2.3/nahook_0.2.3_macos_amd64.tar.gz"
      sha256 "1cfd44b3648ef414bf317670c3c9708bc544c60a30d7d243675bac746a69ec83"

      define_method(:install) do
        bin.install "nahook"
        # Install shell completions generated by the binary so users get
        # tab-complete out of the box when they upgrade via brew.
        generate_completions_from_executable(bin/"nahook", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getnahook/nahook-cli/releases/download/v0.2.3/nahook_0.2.3_macos_arm64.tar.gz"
      sha256 "0b58e2ca20855c816ce2acf3acaa675edf6ccb25d1ee3a55024ef5055fb1b46a"

      define_method(:install) do
        bin.install "nahook"
        # Install shell completions generated by the binary so users get
        # tab-complete out of the box when they upgrade via brew.
        generate_completions_from_executable(bin/"nahook", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getnahook/nahook-cli/releases/download/v0.2.3/nahook_0.2.3_linux_amd64.tar.gz"
      sha256 "5f45d97b881b8d8bb55b90514386cacab0e5c53789d3cca68bf3728e7af1aa81"
      define_method(:install) do
        bin.install "nahook"
        # Install shell completions generated by the binary so users get
        # tab-complete out of the box when they upgrade via brew.
        generate_completions_from_executable(bin/"nahook", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getnahook/nahook-cli/releases/download/v0.2.3/nahook_0.2.3_linux_arm64.tar.gz"
      sha256 "f12c0804c0c809f292ff53431652dc53e33ccc5a3e848335a59bb04c4df975a4"
      define_method(:install) do
        bin.install "nahook"
        # Install shell completions generated by the binary so users get
        # tab-complete out of the box when they upgrade via brew.
        generate_completions_from_executable(bin/"nahook", "completion")
      end
    end
  end

  test do
    system "#{bin}/nahook", "--version"
  end
end
